### ISSUE TITLE
Add SSL/TLS to site

### ISSUE THREAD

**Issue by linhub15** [WonHan7/UAH-Website#1]
# Cloudflare Free SSL/TLS
Cloudflare provides free SSL/TLS certificates https://www.cloudflare.com/

## Adding SSL/TLS
1. Add Site to Cloudflare account
2. Select SSL/TLS
3. Let Cloudflare automatically detect DNS settings from current DNS provider
4. Login to your Domain Name site and set the Name Servers for http://uofahiphop.com to the Cloud Flare name servers
   * there should be 2

## Configuring Page Rules
* Redirecting all `http` traffic to `https` - Always use HTTPS
* Redirecting all `www` traffic to `non-www` - Forwarding URL 301
![image](https://user-images.githubusercontent.com/10420994/94716431-131b9e00-030c-11eb-8009-119c8836676d.png)

**Comment by WonHan7** [comment]
Site now has a valid certificate and uses HTTPS! Thanks linhub15!
